[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "cosmicswag"
client_id = "WH5XzR9MFPVeYdJ2RDrwxsaTVTTpB4Iu"
client_secret = "tbu01rtPymmoy8hWajbQo6o2XyqfcVCaYfaqhxMaEbAKu-OpslTXNpNGDj8MpwQE"
server_metadata_url = "https://dev-7woznghxmces7jvr.us.auth0.com/.well-known/oauth-authorization-server"